### ISSUE TITLE
IfcAlignment 2D representation context map coordinates

### ISSUE THREAD

**Issue by AdamMackellar12d** [bSI-InfraRoom/IFC-Tunnel-Deployment#126]
When we create the 2D geometric context what should we be doing for the map coordinates in 2D, as from the attributes the geometric context would not know about the map coordinates for any geometry referenced by this separate context. 
Is it suitable to just add another IfcMapConversion that references the map coordinates and the new geometric context?

**Comment by pjanck** [comment]
Yes, I believe that having another `IfcCoordinateOperation` would be suitable in this case. The checker does not check this (yet).

**Comment by larswik** [comment]
Ping @AdamMackellar12d . Can you close this?
