### ISSUE TITLE
I don't find any example file for sprint 2.2

### ISSUE THREAD

**Issue by JanErikHoel** [bSI-InfraRoom/IFC-Tunnel-Deployment#127]
I don't find any example file for sprint 2.2
And I don't really understand how to set up the this relation:
IfcTunnelPart.ObjectPlacement.PlacementRelTo shall point to the IfcTunnelPart.Decomposes.RelatingObject.ObjectPlacement

Could you add an example file to the GIT repository - at least I cant see any example file(?)

**Comment by pjanck** [comment]
See #120 and #123 for two example files.

**Comment by JanErikHoel** [comment]
I must admit that even after studying the example-files, I don't understand the difference between the file I submitted and the example file, regarding this aspect. I think I need a detailed explanation of what we should do to establish the correct relative placement.

**Comment by JanErikHoel** [comment]
Hi!

 

Thanks – I now fully understood the concept and have fixed it in my file.

Only one thing left with linear location of ifcReferent that I hope to sort out in the meeting today.

 

Jan Erik
