### ISSUE TITLE
What is status for the schema-specification for the voxels?

### ISSUE THREAD

**Issue by JanErikHoel** [bSI-InfraRoom/IFC-Tunnel-Deployment#139]
What is status for the detailed schema-specification for the voxels?

We're starting a new Quadri developer sprint tomorrow and would like to start implementing the export functionality this week :-)

**Comment by larswik** [comment]
The IfcVoxelGrid (the geometric representation) was merged and updated. Documentation still has to be generated.
For IfcVoxelData (the data for the IfcVoxelGrid) we are planning to have everything ready before start of sprint 3.
There is an example for IfcVoxelGrid in this PR: https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/pull/137 and another one from @ivaroppen here: https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/pull/138

**Comment by JanErikHoel** [comment]
Super - I found your example file and found this - but very good if we just could get the description of the parameters for the #606 ifcVoxelGrid


#4= IFCSITE('1C5xcstzn0f9dSBhtRV3N5',#10,'My site',$,$,#621,$,$,$,$,$,$,$,$);
#10= IFCOWNERHISTORY(#7,#9,$,.ADDED.,1684763855,$,$,1684763855);
#205= IFCGEOMETRICREPRESENTATIONCONTEXT('3D','Model',3,0.0000000254,#206,#569);

#601= IFCGEOSCIENCEMODEL('3$8Mtq0qL3WxJL3y_4_N1i',#10,$,$,$,#605,#608,$,.PHYSICALPROPERTYDISTIBUTIONMODEL.);
#602= IFCRELCONTAINEDINSPATIALSTRUCTURE('18Mjd2_Q8_4n9ME9rMDD7O',#10,'Site','Site Container for Elements',(#601),#4);
#603= IFCCARTESIANPOINT((158765.0,6721390.0,35.0));
#604= IFCAXIS2PLACEMENT3D(#603,$,$);
#605= IFCLOCALPLACEMENT(#3,#604);
#606= IFCVOXELGRID(**3805.0,550.0,50.0,380,55,5,(.T.,**
:
.T.));
#607= IFCSHAPEREPRESENTATION(#205,'Body','Voxel',(#606));
#608= IFCPRODUCTDEFINITIONSHAPE($,$,(#607));

**Comment by pjanck** [comment]
> the description of the parameters for the #606 ifcVoxelGrid

https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/ifcvoxelgrid.htm
