### ISSUE TITLE
sprint3_exc > Support > 2. IfcArchElement/SEGMENT not found in schema

### ISSUE THREAD

**Issue by aothms** [bSI-InfraRoom/IFC-Tunnel-Deployment#173]
See:

- https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/blob/main/sprints/sprint3_exc.md

and 

- https://github.com/bSI-InfraRoom/IFC-Specification/blob/tunnel/IFC4x3/Sections/Shared%20element%20data%20schemas/Schemas/IfcSharedBldgElements/Types/IfcArchElementTypeEnum/DocEnumeration.xml

Am I missing sth? Are we supposed to take the schema from another location? Sorry, I'm not regularly participating in the meetings so I might be somewhat misinformed.

**Comment by SergejMuhic** [comment]
This was a bit of a mess. We still have to add them because the proposal only came in when the psets were specified. We still do not have a consensus on which we should take into the spec but for the sake of the sprint we will for now add the two that are required.

**Comment by aothms** [comment]
Thanks @SergejMuhic. Hope the PR can be merged soon :)

**Comment by SergejMuhic** [comment]
Can we close the issue?
