### ISSUE TITLE
Mandatory Description attribute for IfcDatasetReference

### ISSUE THREAD

**Issue by jmirtsch** [bSI-InfraRoom/IFC-Tunnel-Deployment#21]
https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/ifcdatasetreference.htm
I'd just like confirmation that the attribute Description is mandatory?  Typically an attribute with this description is optional, and documentation doesn't necessarily imply that this attribute should be mandatory.

Thanks,

Jon

**Comment by SergejMuhic** [comment]
@larswik was this intended? I agree with @jmirtsch that it should be optional.

NOTE TO SELF maybe make the default attribute definition optional 😄

**Comment by larswik** [comment]
I've created a PR which already fixes Description as well :-)

**Comment by pjanck** [comment]
Since https://github.com/bSI-InfraRoom/IFC-Specification/pull/501 was merged, I believe we can close this - what do you think @jmirtsch?
