### ISSUE TITLE
Problems with the pull request

### ISSUE THREAD

**Issue by JanErikHoel** [bSI-InfraRoom/IFC-Tunnel-Deployment#31]
Hi!

I THINK I've done everything correct (forking, branching, cloning, adding a file, submitting and then created a pull request), but in the window for pull request I don't get up the cogwheel to choose reviewers and there is no automated checking happening.

Can you see what I've done wrong - or could it be some missing settings somwhere?
![image](https://user-images.githubusercontent.com/48426749/216656299-c0c054ba-b93d-4cc8-9141-ee65f94659b2.png)

**Comment by JanErikHoel** [comment]
It seems that I need to be approved as a first time contributor.

**Comment by pjanck** [comment]
> It seems that I need to be approved as a first time contributor.

Correct. This has been approved now and should allow you for immediate asynchronous feedback on next PRs. 

> I don't get up the cogwheel to choose reviewers

This is interesting. I'll assign us (hopefully this can be done automatically as well).

If your concerns have been addressed, please close the issue. :)

**Comment by JanErikHoel** [comment]
Hmm - I got a test report with failures after you did your magic Stefan, but when I then corrected the file an tried another pull request, I still have problems to get it through - seems that I need write access to the repository...(?)
![image](https://user-images.githubusercontent.com/48426749/216750552-7eb2abcb-b3ca-4c13-8796-032372c9a8e4.png)

**Comment by pjanck** [comment]
It seems somebody needs to approve the action for every commit?! Did not know that before. The action has been started. However, following #25 , it will probably fail, but for known reasons (see also the referenced issue).

**Comment by JanErikHoel** [comment]
Regarding the needed approval: Maybe there are some settings I can adjust on my side?

As far as I understand, so did not Bever and Acca have the same problems - or...?
I changed the file from this:
#15 = IFCGEOMETRICREPRESENTATIONCONTEXT($, 'Model', 3, 1.E-5, #13, #16);

to this:
#15 = IFCGEOMETRICREPRESENTATIONCONTEXT('Model', '3D', 3, 1.E-5, #13, #16);

Could you confirm that this is the correct thing to do - even if the validator fails?
If so, then I'll make a bug fix issue to our developer about this.

**Comment by JanErikHoel** [comment]
The last check reported this back???
Unhandled exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\a\IFC-Tunnel-Deployment\IFC-Tunnel-Deployment\files\Trimble_Quadri\RoadAlignment.ifc files\Trimble_Quadri\RoadAlignment_Rev1.ifc'.

Is this something on your side that fails then, or???
This is the new file I added - I didn't remove the old one. I should probably have done so.

**Comment by pjanck** [comment]
> Is this something on your side that fails

Correct. I see there is a mistake in the action file when handling multiple files. On it!

**Comment by pjanck** [comment]
I believe the correct solution is:

    #15 = IFCGEOMETRICREPRESENTATIONCONTEXT('3D', 'Model', 3, 1.E-5, #13, #16);

**Comment by JanErikHoel** [comment]
But in the example file you have provided the "3D" and "Model" values are switched compared to your comment above?
![image](https://user-images.githubusercontent.com/48426749/216803217-55db1b09-c280-43a1-92b6-f26655ff8a68.png)

**Comment by JanErikHoel** [comment]
Now - I deleted the two existing files, made a new one and tried yet another pull request.

But still I need to wait for approval from one of you (?)
![image](https://user-images.githubusercontent.com/48426749/216803798-746978c6-3a77-43da-80a7-712cd28be769.png)

**Comment by jmirtsch** [comment]
Possibly a user needs a pull request accepted to be acknowledged as a "contributor".
Actions might need to be approved by a moderator until after the first pull request is accepted.

As Stefan commented above, the validation needs a fix for the order of type and identifier
on the geometric context.  https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/issues/25
Until this happens, files that are compliant with the schema will fail.

**Comment by JanErikHoel** [comment]
OK - please let us now when the validation is fixed - and I'll then try with another PR.

**Comment by pjanck** [comment]
Hi @JanErikHoel, I've restarted the check and there seems to be a problem unrelated to #25 in your file: https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/actions/runs/4095165485

You are missing a declaration of some sort, please study Project Declaration [here](https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/blob/main/sprints/sprint1_1.md).

**Comment by pjanck** [comment]
> I see there is a mistake in the action file when handling multiple files.

This has been addressed in #33 .

**Comment by JanErikHoel** [comment]
@pjanck Could the problem in the declaration be that Actor is missing in the file? 
I see that this is a difference between your test file and the file produced by Quadri.

**Comment by SergejMuhic** [comment]
@JanErikHoel you can post directly in your pull request if the issue is specific to the PR. It keeps the issue threads clean and concise.

On to your question. In this sprint we are just testing for the ability of software to declare things properly in `IfcProject` since any instance not directly connected to the project (spatial) breakdown is supposed to be declared (apart from classifications which are associated). Your file is just missing an `IfcRelDeclares`.

https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/project-declaration.htm

**Comment by pjanck** [comment]
@JanErikHoel If we have managed to answer your questions, please close the issue.

**Comment by JanErikHoel** [comment]
Everything is fine - thank you!
