### ISSUE TITLE
IfcUnitAssignment.WR1 fails

### ISSUE THREAD

**Issue by pjanck** [bSI-InfraRoom/IFC-Tunnel-Deployment#76]
Looking [here](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/schema/ifcmeasureresource/lexical/ifcunitassignment.htm):

WR01: Checks that the set of globally assigned units has each unit type (either of type [IfcNamedUnit](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/schema/ifcmeasureresource/lexical/ifcnamedunit.htm),[IfcDerivedUnit](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/schema/ifcmeasureresource/lexical/ifcderivedunit.htm), or [IfcMonetaryUnit](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/schema/ifcmeasureresource/lexical/ifcmonetaryunit.htm)) defined only once.

https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/blob/e386b197631cf08c0a871173fa9679e2076971c9/files/project_team/IFCTunnelDep1.3.ifc#L29-L36

There are two `.PlaneAngleUnit.` assigned.

**Comment by larswik** [comment]
Looks like WR-checking works! I missed that the GeometryGym lib assigned some units (including PLANEANGLEUNIT) per default so the one I added explicitly was not necessary. Fixing.
