### ISSUE TITLE
Question to the concepts: Project Documentation, Project dataset, Project Library

### ISSUE THREAD

**Issue by JanErikHoel** [bSI-InfraRoom/IFC-Tunnel-Deployment#78]
Are these concepts meant to be documentation, dataset and library connected to the PROJECT (like metadata for the whole project) or could they be connected to object types/instances as well? The latter is probably more relevant for Documentation than the other two I guess.

**Comment by SergejMuhic** [comment]
As the documentation says for:
1. Project Document Information
![image](https://user-images.githubusercontent.com/16683597/222954853-d829acff-d3fa-4bb8-82cf-6f3a3501e6a9.png)
2. Same for dataset as we just adjusted the description
3. Project Library Information
![image](https://user-images.githubusercontent.com/16683597/222954918-e33c9e0d-ae17-43b0-9af2-74f239d5809a.png)

All of these templates have `IfcContext` as their root node meaning that they can be applied only to `IfcContext` and its sub classes which are `IfcProject` and `IfcProjectLibrary`.

> like metadata for the whole project

Yes.


> object types/instances as well

No.

> The latter is probably more relevant for Documentation than the other two I guess.

Agree. For attaching documents to objects (we will be doing this also in future sprints) we will be using:
[Document Association](https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/document-association.htm)
![image](https://user-images.githubusercontent.com/16683597/222955154-69257cdd-1a2b-45b9-8850-4afa0d42091b.png)

**Comment by JanErikHoel** [comment]
Everything was answered very well - thank you
